// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6LC8tx1U8zDwgZW5e4pEi7UtWL_MzP84',
    appId: '1:768805427699:web:5f8239095b90627240da86',
    messagingSenderId: '768805427699',
    projectId: 'ngechat-db115',
    authDomain: 'ngechat-db115.firebaseapp.com',
    storageBucket: 'ngechat-db115.firebasestorage.app',
    measurementId: 'G-CXZJQQ3WMM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZx3ya33oaz9HmE5egACz4ZS1_8MonY5g',
    appId: '1:768805427699:android:97b5248030f039fd40da86',
    messagingSenderId: '768805427699',
    projectId: 'ngechat-db115',
    storageBucket: 'ngechat-db115.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPAZxbtMEX5zRbe_gZFQ3u1bu0NnGwH4M',
    appId: '1:768805427699:ios:456d996aea70003c40da86',
    messagingSenderId: '768805427699',
    projectId: 'ngechat-db115',
    storageBucket: 'ngechat-db115.firebasestorage.app',
    iosBundleId: 'com.example.chattingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPAZxbtMEX5zRbe_gZFQ3u1bu0NnGwH4M',
    appId: '1:768805427699:ios:456d996aea70003c40da86',
    messagingSenderId: '768805427699',
    projectId: 'ngechat-db115',
    storageBucket: 'ngechat-db115.firebasestorage.app',
    iosBundleId: 'com.example.chattingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6LC8tx1U8zDwgZW5e4pEi7UtWL_MzP84',
    appId: '1:768805427699:web:19f2d76edaa6cdb140da86',
    messagingSenderId: '768805427699',
    projectId: 'ngechat-db115',
    authDomain: 'ngechat-db115.firebaseapp.com',
    storageBucket: 'ngechat-db115.firebasestorage.app',
    measurementId: 'G-7GJFQCRQX2',
  );
}